[tool.poetry]
name = "llm apps"
version = "1.0.0"
description = "Buidding LLM Apps"
authors = ["Muhammad Awais"]
license = "LLM-1.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
